"use client";
import { useState } from "react";
import { Sparkles, ChevronDown, ChevronUp, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { cn } from "@/lib/utils/cn";

interface AISummaryProps {
  itemId: string;
  initialSummary?: string | null;
}

export function AISummary({ itemId, initialSummary }: AISummaryProps) {
  const [open, setOpen] = useState(!!initialSummary);
  const [summary, setSummary] = useState(initialSummary || "");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSummarize = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ itemId }),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Summarization failed");
      }
      const data = await res.json();
      setSummary(data.summary);
      setOpen(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to summarize");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="rounded-xl border border-border bg-accent-subtle/30 overflow-hidden">
      <button
        onClick={() => {
          if (!summary && !loading) { handleSummarize(); return; }
          setOpen(!open);
        }}
        className="w-full flex items-center gap-2.5 px-4 py-3 text-sm font-medium text-accent hover:bg-accent-subtle/50 transition-colors"
        aria-expanded={open}
      >
        {loading ? (
          <Loader2 className="h-4 w-4 animate-spin shrink-0" />
        ) : (
          <Sparkles className="h-4 w-4 shrink-0" />
        )}
        <span className="flex-1 text-left">
          {loading ? "Generating summary…" : summary ? "AI Summary" : "Summarize with AI"}
        </span>
        {summary && !loading && (
          open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />
        )}
      </button>

      {error && (
        <div className="px-4 pb-3 text-sm text-error">{error}</div>
      )}

      {open && summary && (
        <div className="px-4 pb-4">
          <p className="text-sm text-text-secondary leading-relaxed">{summary}</p>
          <p className="text-xs text-text-tertiary mt-2">Generated by Claude AI</p>
        </div>
      )}
    </div>
  );
}
